services:
  cart-service:
    build:
      context: .
      dockerfile: cart/Dockerfile
    container_name: cart-service
    ports:
      - "8084:8084"
    depends_on:
      sneakers-db:
        condition: service_started
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sneakers-db:5432/sneakersdb?currentSchema=carts_schema
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  orders-service:
    build:
      context: .
      dockerfile: orders/Dockerfile
    container_name: orders-service
    ports:
      - "8082:8082"
    depends_on:
      sneakers-db:
        condition: service_started
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sneakers-db:5432/sneakersdb?currentSchema=orders_schema
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  products-service:
    build:
      context: .
      dockerfile: products/Dockerfile
    container_name: products-service
    ports:
      - "8081:8081"
    depends_on:
      users-service:
        condition: service_started
      sneakers-db:
        condition: service_started
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sneakers-db:5432/sneakersdb?currentSchema=products_schema
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  shipments-service:
    build:
      context: .
      dockerfile: shipments/Dockerfile
    container_name: shipments-service
    ports:
      - "8083:8083"
    depends_on:
      users-service:
        condition: service_started
      sneakers-db:
        condition: service_started
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sneakers-db:5432/sneakersdb?currentSchema=shipments_schema
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  users-service:
    build:
      context: .
      dockerfile: users/Dockerfile
    container_name: users-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sneakers-db:5432/sneakersdb?currentSchema=users_schema
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  sneakers-db:
    image: postgres:15
    container_name: sneakers-db
    environment:
      POSTGRES_DB: sneakersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-dbs:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
